title: ASEAN Social Security Association
url: ""
favicon: /images/favicon22.ico
colors:
  primary-color: "#00568F"
  secondary-color: "#0075C2"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: Resource
description: As a non-government organisation, ASSA seeks to promote the
  development of social security in the region in consonance with the
  aspirations, laws and regulations of the member countries.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://cpfb-test-staging.netlify.app
prod: https://cpfb-test-prod.netlify.app
is_government: false
shareicon: /images/assa-about-logo.png
